language: node_js
sudo: false
node_js:
  - 6.11.1
env:
  - NODE_ENV="test"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
before_script:
  - yarn db:setup:user
  - yarn db:reset
script:
  - yarn test
  - yarn enforce
  - yarn lint
