language: node_js
sudo: false
node_js:
  - 6.11.1
env:
  - NODE_ENV="test"
before_script:
  - yarn db:setup:user
  - yarn db:reset
script:
  - yarn test
  # TODO: Uncomment 'yarn enforce' line below once tests are written.
  # - yarn enforce
  - yarn lint
